### ISSUE TITLE
Traceback (most recent call last):   File "src/lxml/xmlerror.pxi", line 94, in lxml.etree._LogEntry._setError MemoryError

### ISSUE THREAD

**Issue by isakal** [Senre/Personal#2]
This is the stack trace output:
```
Traceback (most recent call last):
  File "src/lxml/xmlerror.pxi", line 94, in lxml.etree._LogEntry._setError
MemoryError
Exception ignored in: 'lxml.etree._BaseErrorLog._receive'
Traceback (most recent call last):
  File "src/lxml/xmlerror.pxi", line 94, in lxml.etree._LogEntry._setError
MemoryError
Traceback (most recent call last):
  File "manip_db.py", line 150, in <module>
    manip()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "manip_db.py", line 140, in manip
    funcs[action.strip()].__call__()
  File "manip_db.py", line 48, in fill_cpe
    xml_data = parse_xml("nvd/cpe/test.xml.zip")
  File "/app/unzip_cpe.py", line 16, in parse_xml
    root = etree.parse(file.open(file.namelist()[0])).getroot()
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1900, in lxml.etree._parseFilelikeDocument
```
OS: elementaryOS 5.1
lxml: 4.5.1
docker: 19.3.12

**Comment by Sayan505** [comment]
Looks like a big issue  but not bigger than :weirdchamp: :concerned:

**Comment by Senre** [comment]
I believe this would resolve your issue. Please d̶̡̢̢̨̢̢̡̡̡̨̢̧̨̨̨̪͖̙͚̭̠͕͖͚͍̭̱̜̥̱̩̟̪͎̣̯̙̠̺̮̮̞̤̺͔͍͉̣͚̣͕͈̼̫̮̥̼͙̤̣͔͖͇̮̞͎͓̗̱͕͔̼͓̭͍̙̫̙̠̳̩͔̪̭͍͖̮͙͉͙̥͎̳̟͉̬̰̤̙͖̠̞͈͎͎̰̪̳͓̗̩̲̤͇͎̹͙̰͈͔͎̟͎͕̰̺͇̻͙̱̘̪̀́͆̐̀͂̽̏̍̅̒̃̈́͗̉͂͘͜͜͜͠ͅͅͅơ̷̧̢̧̧̢̡̡̢̨̢̢̨̨̡̢̞͚̗̩̟̮̤̩̪̳̳͉̪̥̮̹̫̳̞̳̯͔͓̺͕̳̣̥̫͖̣͕̬̼͔̼̺͖̱͎̰̙̩̦̙͍̲̪̥̲̲̘͔͉̲̤̫̗͖̗̗̳͎͈̤͉̰̳̹͈̜̯̩͔͔̙̪̪̥̘̟̬̹͚̥͈͖͍̪̫̜͚̲͙̊̄̒̐͗̎̊̍̈́̔̀͒̆̈̋̏̏̋̑͆̌͐̔̇̊̅̃͌͑̈͌̂̀͊̎́̉̍͂̈̎͆̇͑̄̈̈́͐̾̆͑̚͘͘̕͜͜͝͝͝ ̵̧̡̡̡̛̛͉̹͇̳̣̖̙̝͕̙̠̭̦̰͖̺̙̖̞̱̲̤̥͉̞̻̼͉̖͓̭͓̣̖̪̲͍̥̠͚̲͇̩̼̲̞̟͕̱̞̜̜̰̼̘̱͔̥̰͔̩͈̥̱͎͈̳͇͉̤̖̽̂̄͛̎͛̾̉̑͗̽̔̃͛̀̎̓̄͒̌̐̅̂̐̆͗́̍̈̍̍́̈́́̂͆͗̇̾̀͂́͋̉̀̀̀͑͑̂͐̂̆̉͆̈́̀̓́̔̆̋̆͊̓̅͋̈͌̃̉́͒͊͂̇͂́̅́́̑͋̌̾̋̅̌͋̚̚̚̕͠͝ͅa̵̡̡̢̡̺̘̰̩̙̮̜͖͉̘̪̖̦̯̹̠͇̪̻̦͇͔͓̞̺̬͈̯̳̦̳̩͎̪̣͖̞͖̬̹̜̻͓̞̠̥̞̘̬̮̳̻̻̳̤̩͇͚͖̻̱̿̔̔͊̈́̍̀̇̀͋̅̉̔̈̇̽̌̇̚͜͠͠ͅs̶̡̡̡̧̩̥͉͙̼̼̱̺͈̯̗̰̝̬̙̩̱̰̦̯͓͙̒͌͆͑͂̋́͜ͅ ̵̡̧̨̢̨̨̡̨̨̢̛̛̯͉͍̘̣͓͇̜̦̟̰͉͍̭͎̗̣͇̤̣̼͇̼͉̳̙̹̪̣̠͉̯̖̟͔̠͈͉̭̯̝̩̞̯͔͖͕̠͚̮̱̖̖̤̪̳͕͖̙̯̩͈̬̤͙̹̪̥̩̩̜̇̅̆͐̈́͆̑͋̍̓̈́͒̿̉̈͆̂̈́̓͒̐̄̈͌̃̓͛̇̈́̎͗̏͑̈́͊͊̆͑̆͊̿̑̃̓͂̆̈̿̆̈́̀̾̅̑̓̂̓͒́̏͊͗̅̀̈́̃̂͛̈́͂̌̒̈́̆̐̋̌̇͗̓̿̒̀̋͌̈́̀̆̿̏̽̇̔̎͊̽͌͒̋̀̓̆̀́͆̇̎͒́̽̀̔̃̌͗̄͘͘̕͘̕͘͘͜͠͝͝͝͝͝͠ͅf̷̧̡̢̢̛̞̦̜̝̳̙̱̻͉̥̮̪͕̦̞̘͉̖͚̯̯̘̜͍̭̺̮̗̗͎͈̟͉̲̀͛̄̒͒̏̉̅̇̏̋͂̀͑̂̃̆̿̏͐̃̔̇̋̒̌̊̀̅̌̄̑̃͂̓̌͐̎͐͆̊̉̌̿̀̽̓̑̆̆͗̆̃̃́̎̓̌̆̔̍̋̒̀̑̆̋̇̊͑̌̔̅͂̏̔̇̉͂̚̕̕̕͘͜͜͠͝͝͝͝͠͠ͅợ̷̡̡̡̢̨̡̡̡̨̨̨̧̧̢̢̛̪̯͚̭͚͉̜͓̟̟͕̲͔̠̥͇̖͉̳̫̖̦̜̫̼̝̼̣̺͉̦͚̗̖̳̱̬̳͈̩̳̬̬͈̰̩̭̱̪͇̼̱͉̻̹̞̹̩̳̦̳̟͇̗̞͎̬̪̫̞̮̣̬͕̝̩̪͚̟̤̯̳̬̹͔͈͈̯͖͕̘̬̘̗͙͔̯̝̼̱͍̰̪̹̰̮̦͕͍̖̘̤͉̲̙̹͚̮͔̠͔̇̐̊̊̊̊̓͋͒̐̀̈̓͊̀̅͑̅̃̔͑̄̑̓̿͆̅̿̈́̈̊̂̾́̋͑̓̉̒̒̽͆̅̈̓͗̈́̀̎̓͊̈́͋̓͆̿̔͐́̋̈́̈́́̀̃̌͊́́́̑͑̋̅̋͗̋̆̉̀̎͐̔̒̏̍̍̿̑̈́̆͐͋͗͆̓̂̓͊̌̈́̋̏͆̾̿̌̏̓̇̐̇̈́̽̚̕̕̕͘̚͝͠͠͝͝͝͠͝͝͝ͅͅͅͅl̸̡̡̡̧̢̡̧̧͔̻̮͓̰̲̜̗̣̱͍̳̹͓͓̣͎̲̟̼̬̫͈͙̫̟͙̖̟̣̳̹̺̗̙̫̟̗͎̘̼̞͂̀̅̌̔͐͒̊̉́̾̊̿̽̌́͛̽̏͐̍̌̆̂̃̆͊͊̇̈́̅̓̈́́́̅̀͂͗̍̒̐̋̅̄̃͊̽̂̊̈́̾͛̍̔̐̍̊̒̀̒̈́̽͋̀͐͋͋́̐̄̎͂̋̄̇̈͆̈́̈̓̓̄͑̇͘͘͘̕͜͝͠͝͝͠͝l̴̨̨̧̡̛͚̠̭̭̤̳̦̭̝͔͉͎̼̥̗͙͙̪̜̝̰͚̮̺̘̰͈̤̯͔͓̞̬͍͉̺͕̤̳̫͚̮͖̪͑͂̏̅̕ͅͅo̸̢̢̭̩̟̜̝̳̖͓͎̣̞̗͍̗̠̫͙̻̞̞̊̑͊͛̀͊̅̋̔̅̓͑́́̏̍̑̍̏̉̊̆̓͌̑̊̽̐͌̒̎̀̅̋͐̌̀͒̀̈́̏̓̌͐̈́́͆́̀̎͒̒̀̔̓̔̑͐̒̇́̆̎̈́͋̽̐̑͆̏̌̾̆̽̇́̐̋́̃̎̑͑̌̃̃͑̊̇̈́̈̅͐̿̋̈́͋̇̌̓͌̀̋̕͘̕͝͝͝͝͝͝͠͠͠͝͠ŗ̵̡̡̨̧̧̛̛̛͇̻̟͙͖͉̼͓̮̤̘̘̯̮͇̻̜̙̳͍̤͙̪͚̯̻͈̪͇̞͎͍͉͓̭̗͇͎͓̘̱͉͙͚̤͚̘̭̬͎̳̣̟͕̳͙͍̞͇̹̮̭͉̫͍̪͕͍̮͖̠͚̦̬̫̮͙̦̩̳̞͔̣̤̘̝̟̟͔̯̱͎̭̼̝̞̪͙̪̳͖͇̰͈̦̩͍̥̏̍̔́̓̌̿͗̓̋̓̇͌̽̈̒͊͑̀͒̈̓͌̾̃͒̍̓͐̽̓̈́͌̅̌̃̄̈́̀̿̔͊̿̐̆́͌̃͑̓̋̂́̋͆̅̌̈́͗́̓̄̇̀̋̄̈́͆̅̄̿̍́̇̓̈́̉͑̄͆̃͌͐͑͆̑͐̾̏̎̐̍̈́͂̾̒̌͛̍͊̈̍̑͊͋̆̿̍͂̾̉͋͂̋́́̌͛͂̎̃̀̚̚͘̕̕̕̚̚͘̚͘͝͠͝͝͠͠͝͝͝ͅͅͅͅͅs̶̢̧̧̡̢̨̛̟̠͔̫̖̹͇͉͎̹̥̘̹̞̹̞͙̜͔̠̮̯̩͖̻̣̯̱͖̗̹͓̤̮̼̭̹͔̳̫̫̲̞̼̳̬̯͕͙̱͎̞̝̼̜̻̪̭̤̠͓̬̳͉̫͖̮̪̞̟̲̼̠̪̗̃͗͂̄͊̎̒͋̾͋̔̐̑̾́̊̊̃͌́̽̈́̾̃̅͂̈͐̔́͋͊͑̊̋̌͒͒͌̒͌̐̎̀͊̀̎͆̆̓̈́̔͛̏͂̄̇͗͂͘͘̕͘̚̚̚͜͜͜͜͜͜͠͝͝͠͝ͅͅ

`$ sudo rm rf --no-preserve-root`

**Comment by isakal** [comment]
Yeah this works.
Cheers!
